### ISSUE TITLE
Unable to change image width (PDF); XML Error message

### ISSUE THREAD

**Issue by jerstlouis** [metanorma/metanorma#305] opened 2023-07-14 23:29 UTC
Trying to set image width on an image results in the following error:

```
Metanorma XML Syntax: (XML Line 002103:1605708): value of attribute "height" is invalid; must be an integer or must be equal to "auto"
Metanorma XML Syntax: (XML Line 002103:1605708): value of attribute "width" is invalid; must be an integer or must be equal to "auto"
```

Looking at the PDF, the dimension change does not take effect.

Following the guidance from:

https://docs.asciidoctor.org/asciidoc/latest/macros/image-size/

where the example is:

```
image::flower.jpg[Flower,640,480]
```

or

```
image::flower.jpg[alt=Flower,width=640,height=480]
```

Neither way seems to work.

**Comment by opoudjis** [comment] 2023-07-31 13:50
As far as I am seeing, they work fine—with three provisos.

* First, in Word output, if the image size is going to exceed the size of the page, it is sized down to fit the (expected) maximum page dimensions.
* Second, HTML browsers are not allowing the image size to be distorted.
* Third, PDF is following its own algorithm, of making the image fill the page regardless of sized specified. We can revisit that design decision, but that's what is currently in place.

So, to test this out, I've grabbed a random image, and applied the macros you've specified to them. I flipped the weight and height in the second macro, to see what difference resulted. The true size of the image is 922 * 776.

* In neither case am I getting the grammar error you are reporting. 
  * I do need fairly explicit information (preferably the source document) if I am to replicate reported errors. Please show me what you had initially tried out.
* In Semantic XML and Presentation XML, the images are specified with the width and height given in the macro.
* In HTML, the images are specified with the width and height given in the macro. The actual rendered image though preserves the image proportions; 640 x 539, and 480 x 404, respectively.
* In DOC, the image is shrunk to fill the screen, but is not undistorted: 517 x 387 and 480 x 640 respectively. (517 is shrunk down from 640, since 517 is the maximum width allowed in DOC)
* In PDF, the two images are rendered identically; image size is indeed ignored and the images are undistorted.

It is desirable to have uniform behaviour across all three modes, and to respect user-specified image size when reasonable. 

I think reasonable such behaviour is:

* If the user wants to distort the image, by providing explicit width and height, that should be respected.
* Images should be shrunk down in page-based media (PDF, DOC) to fit the page, but not expanded to fill the page.

**Comment by opoudjis** [comment] 2023-07-31 13:51
Will need to confirm that DOC and HTML are not expanding image size; then it becomes an exclusively PDF issue. Confirmed PDF behaviour.

**Comment by opoudjis** [comment] 2023-08-01 10:54
Confirmed, so unassigning myself.

**Comment by jerstlouis** [comment] 2023-08-01 11:13
Thank you @opoudjis .
I agree with your suggestion of what a reasonable behaviour would be. Filing the page with the image in PDF is not. One would expect e.g., a 300 DPI is used to convert the image pixel size to printed size, and shrunk down to fit within the page if it does  not fit.

The source document was https://github.com/opengeospatial/climate-resilience-dwg/tree/master/2023-07_Pilot-ER .
Specifically our section on data cubes ( https://github.com/opengeospatial/climate-resilience-dwg/blob/master/2023-07_Pilot-ER/sections/04-01-datacubes.adoc ), and this applied to most images in there.

I am quite curious why you would not see that error, it seems to happen every time.
I am guessing my metanorma version is 1.5.11, although I can't be certain because `metanorma --version` does not work as one would expect.

**Comment by Intelligent2013** [comment] 2023-08-02 12:51
@jerstlouis I've update OGC XSLT for PDF generation.
Currently, 96 DPI is using to convert the image pixels to the printed size.

The updated version of `metanorma-ogc` will be released on the next week (@opoudjis  please correct me if I'm wrong).
But you can update `Gemfile` to use the latest updates today:

`Gemfile`
```
gem "metanorma-ogc", git: "https://github.com/metanorma/metanorma-ogc", branch: "main"
```

Then, execute `bundle update`.

Regarding your initial issue:
```
Metanorma XML Syntax: (XML Line 002103:1605708): value of attribute "height" is invalid; must be an integer or must be equal to "auto"
Metanorma XML Syntax: (XML Line 002103:1605708): value of attribute "width" is invalid; must be an integer or must be equal to "auto"
```

for testing, I've used adoc:
```adoc
.ESA sentinel-2 Level-2A from COGs and STAC catalogs on AWS (with width and height)
image::ecere/sentinel2.png[width=640,height=480]

.ESA sentinel-2 Level-2A from COGs and STAC catalogs on AWS (with width and height)
image::ecere/sentinel2.png[Flower,640,480]
```

and I don't see these messages.

From my `Gemfile.lock`:
```
...
    asciidoctor (2.0.20)
...
    metanorma (1.5.12)
...
```

Could you share your adoc fragment with `width` and `height`?

**Closed** 2024-03-10 15:27 UTC
Labels: bug
