### ISSUE TITLE
"Invalid argument @ dir_s_mkdir" when running collection.rb on Windows

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/metanorma#386] opened 2024-05-15 02:53 UTC
When I run this:
```
bundle exec ruby collection.rb
```

From [iso-10303-srl](https://github.com/metanorma/iso-10303-srl), I get this error on Windows:
```
C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir': Invalid argument @ dir_s_mkdir - documents/output/C: (Errno::EINVAL)
        from C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'
        from C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
        from C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'
        from C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'
        from C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:211:in `each'
        from C:/Ruby27-x64/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/bundler/gems/metanorma-dee9ac3ee7ca/lib/metanorma/collection_fileprocess.rb:52:in `copy_file_to_dest'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/bundler/gems/metanorma-dee9ac3ee7ca/lib/metanorma/collection_fileprocess.rb:64:in `block in files'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/bundler/gems/metanorma-dee9ac3ee7ca/lib/metanorma/collection_fileprocess.rb:61:in `each'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/bundler/gems/metanorma-dee9ac3ee7ca/lib/metanorma/collection_fileprocess.rb:61:in `each_with_index'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/bundler/gems/metanorma-dee9ac3ee7ca/lib/metanorma/collection_fileprocess.rb:61:in `files'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/bundler/gems/metanorma-dee9ac3ee7ca/lib/metanorma/collection_renderer.rb:80:in `render'
        from C:/Ruby27-x64/lib/ruby/gems/2.7.0/ruby/2.7.0/bundler/gems/metanorma-dee9ac3ee7ca/lib/metanorma/collection.rb:106:in `render'
        from collection.rb:238:in `main'
        from collection.rb:290:in `<main>'
```

**Comment by opoudjis** [comment] 2024-05-15 03:34
I was sure I was checking that the file was absolute before concatenating it, but Windows is gonna be Windows. Will try to work out.

**Comment by opoudjis** [comment] 2024-05-15 03:52
This is the issue:

````
 def copy_file_to_dest(identifier)
      dest = File.join(@outdir, @files.get(identifier, :out_path))
      FileUtils.mkdir_p(File.dirname(dest))
      FileUtils.cp @files.get(identifier, :ref), dest
    end
````

`@files.get(identifier, :out_path))` is now absolute, not relative, so I can't be just joining it into the output directory. On Mac, this is resulting in the entire root directory tree being replicated, as Ronald has just found:

![image](https://github.com/metanorma/metanorma/assets/1911039/22c2a8f3-347f-4643-96c7-f0dbacdfc517)

The fix is to keep both the relative and the absolute path available for the file, and to use the relative, not the absolute path, to generate the output destination of the file.

**Comment by opoudjis** [comment] 2024-05-16 10:07
In fact, the issue is in

````
 def file_entry(ref, identifier)
      ref["fileref"] or return
      out = ref["attachment"] ? ref["fileref"] : File.basename(ref["fileref"])
````

The existing code has:

* If this is an attachment, put the output file for it in something that reproduces the source document tree in the output directory (because attachments can be all over the place in the document tree)
* If this is a normal document, put the output file for it at the top of the output directory, because all normal documents should be just at the top of the output directory

That's... not a  reliable criterion, and the real solution should be to just put the output files, whether attachment or not, in something that replicates the source directories. But I'm worried about breaking too much at once.

This is now breaking because ref["fileref"] is now an absolute reference, and the code to copy files out to the output directory is assuming that ref["out_path"], the destination address computed here, is a relative reference to be concatenated to the output directory.

I am recording the original relative path as ref["fileref_orig"], and I will now use that to calculate the location of output files. I will defer any replication of source directory structure for document files, i.e. getting rid of ` File.basename(ref["fileref"])`, until a lot later. There is too much instability right now.

**Comment by ronaldtse** [comment] 2024-05-16 10:36
Let’s just stop using the hash. I demand we stop using the hash for any serious operation.

**Comment by opoudjis** [comment] 2024-05-16 11:07
The refactor to leave behind hashes was what I started on Monday, and you interrupted it on Tuesday with your boneheaded last minute request to introduce relative paths, after you assured me on Monday that you were ready to go with the demo.

I am now going to make this PR work BEFORE I go back to the other PR that is aimed to doing away with the hash, and I DEMAND that you not make it harder for me to do so than it already is by inserting random uninformed bogus unhelpful demands.

**Comment by opoudjis** [comment] 2024-05-16 11:16
As I was saying, I am now having to track both the absolute path of the file, determined to address the problem with nested YAMLs in different random locations, and the original relative paths of the files, which we would like to preserve in order to replicate the file structure in output. This state of affairs isn't great, and I'd like to eventually rationalise it with a single absolute path, and then calculation of relative output paths all together based on an inferred common path prefix (which may or may not be the working directory); but I simply cannot do that right now. I will persist the solution of a distinct fileref and (optional) fileref_original into the Shale solution, and then undo it once the Shale solution stabilises.

**Comment by opoudjis** [comment] 2024-05-16 11:29
No, that really isn't going to work... 

I'm going to introduce that factoring out from the absolute path of the base path up front.

**Comment by opoudjis** [comment] 2024-05-16 11:41
It turns out I was already differentiating what is now the absolute and the relative paths in FilesLookup class. But that means I now can't replicate this behaviour in Rspec. Confused...

**Comment by opoudjis** [comment] 2024-05-16 13:05
Confirmed. So:

Now we have working directory collection.yaml, pointing to documents/10303-42/collection.yaml, pointing to ../../schema_docs/scan_data_3d_shape_model_schema/doc_scan_data_3d_shape_model_schema.html

That attachment is ending up at documents/output/documents/iso-10303-42/../../schema_docs/scan_data_3d_shape_model_schema/doc_scan_data_3d_shape_model_schema.html

````
cp /Users/nickn/Documents/Arbeit/upwork/ribose/iso-10303-srl/documents/iso-10303-42/../../schema_docs/scan_data_3d_shape_model_schema/doc_scan_data_3d_shape_model_schema.html documents/output/documents/iso-10303-42/../../schema_docs/scan_data_3d_shape_model_schema/doc_scan_data_3d_shape_model_schema.html
````

Let's generalise this as: 

We have working directory YAML A, pointing to YAML at B/*.yaml (relative to A), which points to file at C (relative to B). We want to output it to output directory D (relative to A).

We need the absolute path of C, and the relative path of copying C to D, while preserving its document tree, relative to B, or preferably A.

The absolute path of C is File.join(A, B, C). The ".." in the tree take care of going back up the tree.

The absolute path of C is set in CollectionManifest.documents(dir). The argument dir passed to CollectionManifest.documents(dir) is B, the directory containing B/*.yaml. That directory is set in Collection.initialize: it is at the moment File.extend_path(File.dirname(args[:file])), where args[:file] is the YAML file of the collection manifest.

If we are going to recursively allow YAMLs to chain indefinitely, that args[:file] is going to need to always be absolute, whenever we read a new YAML. I think the code manages that, but it needs testing.

That File.extend_path in Collection.initialize was inserted to make the file path to the directories absolute.

The destination path for C is right now currently File.join(D, B, C1), where C1 is a sanitised version of C (out_path). That sanitisation right now does two things:

* strip initial "../.."
* add disambiguating numbers if there is a clash with another file already going to the same file location. 

That however is now no longer working. The paths are not being treated blindly as relative, but are being prefixed, so the initial ../.. is no longer initial in .../documents/iso-10303-42/../../schema_docs . This works for now, because the files being invoked are still inside the working directory: schema_docs is a child directory of iso-10303-srl. But in the general case, that cannot be guaranteed: if the attachments were outside the working directory, e.g. ../../../schema_docs, the output directory stops being self contained.

So I need to do extra sanitisation for that case, and insert test code for it.

This all takes time, and I will not be rushed on it.

**Comment by opoudjis** [comment] 2024-05-16 14:24
implemented fix, but I need to add testcase

**Comment by opoudjis** [comment] 2024-05-16 15:50
The fileref_resolver @kwkwan no longer needs to return an absolute value, but if it returns a relative value, that value does need to be relative to the current YAML location. This is affecting test case.

**Comment by opoudjis** [comment] 2024-05-16 16:05
compile_adoc_documents(collection_model) has no idea where the calling YAML is located, so if we are not relying on fileref_resolver to resolve relative links (and we need not to), the routine has no idea where any of the asciidoc files are located.

This is wrong. I am getting rid of compile_adoc_documents as a batch processor. I am going to run the parse during parsing of the individual docref instances, in the loop of docref_from_document_and_attachments, which goes through the individual files once it does know where they are located.

In the more general case, YAML also needs to be handled wherever it is found in that way, as files are iterated.

I am going to have to clean up all of this. @kwkwan @ronaldtse DO NOT do any work on metanorma until I have resolved all of this.

**Comment by opoudjis** [comment] 2024-05-16 16:14
In fact, compile_adoc needs to move inside of Manifest processing, instead of before Manifest processing for the "new" structure, as it is now. The Adoc needs to be compiled as soon as the manifest sees it.

docref_from_document_and_attachments is an illegitimate filter, also.

**Comment by opoudjis** [comment] 2024-05-16 17:07
I have to stop now, it's 3 am (again), but I'm tying myself up in knots because the manifest processor does not know what the YAML location is, to work out where the files are for relative links, if there will be YAML indirection. I was making do with the location being established in subsequent processing, FilesLookup => Document; but I need to know at manifest time, so I can parse adoc as I find them. So manifest processing needs to know the file location the manifest is retrieved from: pass the file location in .from_yaml and .from_xml

**Comment by opoudjis** [comment] 2024-05-16 17:43
Next issue unearthed in testing: sectionsplit is not coping with difference between YAML location and working directory either. And I am still introducing test case to ensure that attachment locations respect absolute locations and locations outside of working directory.

**Comment by opoudjis** [comment] 2024-05-17 10:56
So now testing how indirect YAML => sectionsplit, absolute paths of attachments, and paths of attachments outside the working directory, all interact, in order to ensure that path generation is solid.

**Comment by opoudjis** [comment] 2024-05-17 11:25
Done, have complete test suite dealing with all of these now (and that would have caught the absolute attachment paths that this ticket is addressing). Now testing on ISO-10303-41 and -42.

**Comment by opoudjis** [comment] 2024-05-17 11:40
The attachments are ending up in the right places. I'm closing this issue.

**Closed by opoudjis** 2024-05-17 11:40 UTC
Labels: bug
